const products = [
    {
        id: 0,
        name: "Bamboo Palm Plant",
        ogprice: 499,
        price: 380,
        badge: "Bestseller",
        imgsrc: "./images/indoor-plants.jpg",
        instock: 20,
        category: "medium fourninenine four three two air instock",
    },
    {
        id: 1,
        name: "Aloe Vera",
        ogprice: 200,
        price: 160,
        badge: "SALE",
        imgsrc: "./images/aleovera-plant.jpg",
        instock: 10,
        category: "small oneNineNine four three two instock",
    },
    {
        id: 2,
        name: "Rubber Plant",
        ogprice: 649,
        price: 499,
        badge: "SALE",
        imgsrc: "./images/rubber-plant.jpg",
        instock: 10,
        category: "medium fourninenine four three two air instock",
    },
    {
        id: 3,
        name: "Snake Plant",
        ogprice: 999,
        price: 799,
        badge: "Bestseller",
        imgsrc: "./images/snake-plant.jpg",
        instock: 20,
        category: "small nineNineNine four three two instock",
    },
    {
        id: 4,
        name: "Cactus",
        ogprice: 549,
        price: 399,
        badge: "SALE",
        imgsrc: "./images/cactus-plant-elongated.jpg",
        instock: 10,
        category: "small fourninenine four three two instock",
    },
    {
        id: 5,
        name: "Lemon Grass",
        ogprice: 799,
        price: 499,
        badge: "SALE",
        imgsrc: "./images/lemon-grass.jpg",
        instock: 20,
        category: "medium fourninenine four three two instock",
    },
    {
        id: 6,
        name: "Chlorophytum Spider Plant",
        ogprice: 499,
        price: 249,
        badge: "SALE",
        imgsrc: "./images/spider-plant.jpg",
        instock: 20,
        category: "small fourninenine four three two air instock",
    },
    {
        id: 7,
        name: "Tiger Tooth Aloe Vera",
        ogprice: 200,
        price: 149,
        badge: "SALE",
        imgsrc: "./images/tiger-tooth-aloevera.jpeg",
        instock: 20,
        category: "small oneNineNine four three two medicinal instock",
    },
    {
        id: 8,
        name: "Money Plant - Golden",
        ogprice: 299,
        price: 249,
        badge: "Bestseller",
        imgsrc: "./images/money-plant-golden.jpg",
        instock: 20,
        category: "small fourninenine four three two hanging instock",
    },
    {
        id: 9,
        name: "English Ivy",
        ogprice: 399,
        price: 149,
        badge: "SALE",
        imgsrc: "./images/english_ivy.jpg",
        instock: 20,
        category: "small oneNineNine four three two hanging instock",
    },
    {
        id: 10,
        name: "Snake Plant - Golden",
        ogprice: 549,
        price: 349,
        badge: "SALE",
        imgsrc: "./images/snake-plant-golden.jpg",
        instock: 20,
        category: "small fourninenine four three two succulents instock",
    },
    {
        id: 11,
        name: "Jade Plant Mini",
        ogprice: 499,
        price: 249,
        badge: "Bestseller",
        imgsrc: "./images/mini-jade-plant.jpg",
        instock: 20,
        category: "medium fourninenine four three two instock",
    },
    {
        id: 12,
        name: "Monstera Plant",
        ogprice: 1299,
        price: 799,
        badge: "Bestseller",
        imgsrc: "./images/monstera-plant.jpg",
        instock: 20,
        category: "medium large nineNineNine four three two instock",
    },
    {
        id: 13,
        name: "Echeveria Pegasus",
        ogprice: 359,
        price: 249,
        badge: "SALE",
        imgsrc: "./images/echeveria-Pegasus.jpg",
        instock: 20,
        category: "small fourninenine four three two air instock",
    },
    {
        id: 14,
        name: "Turtle Vine",
        ogprice: 999,
        price: 799,
        badge: "SALE",
        imgsrc: "./images/turtle-vine.webp",
        instock: 20,
        category: "medium fourninenine four three two cactus instock",
    },
    {
        id: 15,
        name: "Haworthia Cymbiformis Plant",
        ogprice: 459,
        price: 249,
        badge: "SALE",
        imgsrc: "./images/haworthia-Cymbiformis-Plant.jpg",
        instock: 20,
        category: "medium nineNineNine four three two hanging instock",
    },
    {
        id: 16,
        name: "Rosemary Plant",
        ogprice: 499,
        price: 399,
        badge: "Bestseller",
        imgsrc: "./images/rosemary-plant.jpg",
        instock: 20,
        category: "medium fourninenine four three two medicinal instock",
    },
    {
        id: 17,
        name: "Heart Hoya Plant",
        ogprice: 449,
        price: 349,
        badge: "SALE",
        imgsrc: "./images/heartHoya.jpg",
        instock: 20,
        category: "small fourninenine four three two cactus instock",
    },
    {
        id: 18,
        name: "Tulsi Plant",
        ogprice: 299,
        price: 149,
        badge: "Bestseller",
        imgsrc: "./images/tulsi-plant.jpg",
        instock: 20,
        category: "small medium oneNineNine four three two medicinal instock",
    },
    {
        id: 19,
        name: "Echinocactus Grusonii",
        ogprice: 499,
        price: 399,
        badge: "SALE",
        imgsrc: "./images/echinocactusGrusonii.jpeg",
        instock: 20,
        category: "medium fourninenine four three two cactus instock",
    },
    {
        id: 20,
        name: "Spider Plant With Hanging Pot",
        ogprice: 1299,
        price: 899,
        badge: "Bestseller",
        imgsrc: "./images/spider-plant-hanging.jpg",
        instock: 20,
        category: "medium nineNineNine four three two hanging instock",
    },
    {
        id: 21,
        name: "TRADESCANTIA PINK",
        ogprice: 499,
        price: 199,
        badge: "SALE",
        imgsrc: "./images/TRADESCANTIAPINK.jpeg",
        instock: 20,
        category: "small oneNineNine four three two instock",
    },
    {
        id: 22,
        name: "Monstera Deliciosa Plant",
        ogprice: 1299,
        price: 799,
        badge: "Bestseller",
        imgsrc: "./images/monstera-dilecta.jpg",
        instock: 20,
        category: "medium large nineNineNine four three two instock",
    },
    {
        id: 23,
        name: "Ficus Bonsai Plant",
        ogprice: 999,
        price: 799,
        badge: "Bestseller",
        imgsrc: "./images/ficus.jpg",
        instock: 20,
        category: "medium nineNineNine four three two instock",
    },
]